import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is generated automatically from the folder structure and the
 * `_category_.json` files in each directory. Per-doc ordering is controlled by
 * the `sidebar_position` front matter in each markdown file.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
